//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roman_DB_CURSED
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CalcEntities : DbContext
    {
        public CalcEntities()
            : base("name=CalcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<measure> measure { get; set; }
        public virtual DbSet<nom> nom { get; set; }
        public virtual DbSet<nomtype> nomtype { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<orderstatus> orderstatus { get; set; }
        public virtual DbSet<prodstage> prodstage { get; set; }
        public virtual DbSet<resspec> resspec { get; set; }
        public virtual DbSet<resspecnoms> resspecnoms { get; set; }
        public virtual DbSet<storage> storage { get; set; }
        public virtual DbSet<storagecontains> storagecontains { get; set; }
        public virtual DbSet<subdivision> subdivision { get; set; }
        public virtual DbSet<techmap> techmap { get; set; }
    }
}
