//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roman_DB_CURSED
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumptionlog
    {
        public int NomId { get; set; }
        public int ProductionLogId { get; set; }
        public Nullable<decimal> NomCount { get; set; }
    
        public virtual nom nom { get; set; }
        public virtual productionlog productionlog { get; set; }
    }
}
