//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roman_DB_CURSED
{
    using System;
    using System.Collections.Generic;
    
    public partial class nom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nom()
        {
            this.order = new HashSet<order>();
            this.resspecnoms = new HashSet<resspecnoms>();
            this.storagecontains = new HashSet<storagecontains>();
        }
    
        public int NomId { get; set; }
        public int MeasureId { get; set; }
        public int NomTypeId { get; set; }
        public Nullable<int> TechMapId { get; set; }
        public string NomName { get; set; }
        public string NomDesc { get; set; }
        public Nullable<int> ResSpecId { get; set; }
    
        public virtual measure measure { get; set; }
        public virtual nomtype nomtype { get; set; }
        public virtual resspec resspec { get; set; }
        public virtual techmap techmap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resspecnoms> resspecnoms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<storagecontains> storagecontains { get; set; }
    }
}
