//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roman_DB_CURSED
{
    using System;
    using System.Collections.Generic;
    
    public partial class productionlog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productionlog()
        {
            this.consumptionlog = new HashSet<consumptionlog>();
        }
    
        public int ProductionLogId { get; set; }
        public System.DateTime ProdStageStartTime { get; set; }
        public int ProdStageActualDuration { get; set; }
        public Nullable<decimal> NomCount { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProdStagId { get; set; }
        public Nullable<int> TechMapId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumptionlog> consumptionlog { get; set; }
        public virtual order order { get; set; }
        public virtual prodstage prodstage { get; set; }
    }
}
