//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roman_DB_CURSED
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodstage
    {
        public int TechMapId { get; set; }
        public int ProdStagId { get; set; }
        public string ProdStageName { get; set; }
        public System.TimeSpan ProdStageDuration { get; set; }
        public int SubDivisionId { get; set; }
        public Nullable<int> ProdStageNextStage { get; set; }
    
        public virtual subdivision subdivision { get; set; }
        public virtual techmap techmap { get; set; }
    }
}
