--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 25.05.2021 23:50:20
-- Server version: 5.7.33-log
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Dumping data for table resspec
--
-- Table test3.resspec does not contain any data (it is empty)

-- 
-- Dumping data for table measure
--
INSERT INTO measure VALUES
(13, 'Кг'),
(14, 'м.'),
(15, 'шт.');

-- 
-- Dumping data for table techmap
--
INSERT INTO techmap VALUES
(2, 'Производство Платы в сборке'),
(3, 'Производство Корпуса'),
(4, 'Производство Платы');

-- 
-- Dumping data for table subdivision
--
INSERT INTO subdivision VALUES
(7, 'Паяльный цех'),
(8, 'Сборочный цех'),
(9, 'Производство корпусов'),
(10, 'Производство печатных плат');

-- 
-- Dumping data for table orderstatus
--
-- Table test3.orderstatus does not contain any data (it is empty)

-- 
-- Dumping data for table nom
--
-- Table test3.nom does not contain any data (it is empty)

-- 
-- Dumping data for table prodstage
--
INSERT INTO prodstage VALUES
(4, 1, 'Очистка платы от краски', '1 00:00:00', 10, NULL);

-- 
-- Dumping data for table `order`
--
-- Table test3.`order` does not contain any data (it is empty)

-- 
-- Dumping data for table storage
--
-- Table test3.storage does not contain any data (it is empty)

-- 
-- Dumping data for table productionlog
--
-- Table test3.productionlog does not contain any data (it is empty)

-- 
-- Dumping data for table storagecontains
--
-- Table test3.storagecontains does not contain any data (it is empty)

-- 
-- Dumping data for table resspecnoms
--
-- Table test3.resspecnoms does not contain any data (it is empty)

-- 
-- Dumping data for table consumptionlog
--
-- Table test3.consumptionlog does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;