--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28.05.2021 17:37:55
-- Server version: 5.7.33-log
-- Client version: 4.1
--

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

SET NAMES 'utf8';

USE test3;

DROP TABLE IF EXISTS storagecontains;

DROP TABLE IF EXISTS storage;

DROP TABLE IF EXISTS consumptionlog;

DROP TABLE IF EXISTS productionlog;

DROP TABLE IF EXISTS `order`;

DROP TABLE IF EXISTS orderstatus;

DROP TABLE IF EXISTS prodstage;

DROP TABLE IF EXISTS subdivision;

DROP TABLE IF EXISTS resspecnoms;

DROP TABLE IF EXISTS nom;

DROP TABLE IF EXISTS techmap;

DROP TABLE IF EXISTS measure;

DROP TABLE IF EXISTS resspec;

USE test3;

CREATE TABLE resspec (
  ResSpecId int(11) NOT NULL AUTO_INCREMENT,
  ResSpecName text NOT NULL,
  PRIMARY KEY (ResSpecId)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE measure (
  MeasureId int(11) NOT NULL AUTO_INCREMENT,
  MeasureName text NOT NULL,
  PRIMARY KEY (MeasureId)
)
ENGINE = INNODB,
AUTO_INCREMENT = 17,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE techmap (
  TechMapId int(11) NOT NULL AUTO_INCREMENT,
  TechMapName text NOT NULL,
  PRIMARY KEY (TechMapId)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE nom (
  NomId int(11) NOT NULL AUTO_INCREMENT,
  MeasureId int(11) NOT NULL,
  TechMapId int(11) DEFAULT NULL,
  NomName text NOT NULL,
  NomDesc text DEFAULT NULL,
  ResSpecId int(11) DEFAULT NULL,
  PRIMARY KEY (NomId)
)
ENGINE = INNODB,
AUTO_INCREMENT = 31,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

ALTER TABLE nom
ADD INDEX IX_Relationship10 (TechMapId);

ALTER TABLE nom
ADD CONSTRAINT FK_nom_measure_MeasureId FOREIGN KEY (MeasureId)
REFERENCES measure (MeasureId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE nom
ADD CONSTRAINT FK_nom_resspec_ResSpecId FOREIGN KEY (ResSpecId)
REFERENCES resspec (ResSpecId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE nom
ADD CONSTRAINT FK_nom_techmap_TechMapId FOREIGN KEY (TechMapId)
REFERENCES techmap (TechMapId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE resspecnoms (
  NomId int(11) NOT NULL,
  ResSpecId int(11) NOT NULL,
  NomCount decimal(20, 10) NOT NULL,
  PRIMARY KEY (NomId, ResSpecId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 862,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

ALTER TABLE resspecnoms
ADD CONSTRAINT FK_resspecnoms_nom_NomId FOREIGN KEY (NomId)
REFERENCES nom (NomId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE resspecnoms
ADD CONSTRAINT Relationship7 FOREIGN KEY (ResSpecId)
REFERENCES resspec (ResSpecId);

CREATE TABLE subdivision (
  SubDivisionId int(11) NOT NULL AUTO_INCREMENT,
  SubDivisionName text NOT NULL,
  PRIMARY KEY (SubDivisionId)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE prodstage (
  TechMapId int(11) NOT NULL,
  ProdStagId int(11) NOT NULL AUTO_INCREMENT,
  ProdStageName text NOT NULL,
  ProdStageDuration int(11) NOT NULL,
  SubDivisionId int(11) NOT NULL,
  ProdStageNextStage int(11) DEFAULT NULL,
  ProdStageIndex int(11) NOT NULL,
  PRIMARY KEY (ProdStagId),
  UNIQUE INDEX UK_prodstage_ProdStagId (ProdStagId)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

ALTER TABLE prodstage
ADD INDEX UK_prodstage_TechMapId (TechMapId);

ALTER TABLE prodstage
ADD CONSTRAINT FK_ProdStage_Subdivision_SubdivisionId FOREIGN KEY (SubDivisionId)
REFERENCES subdivision (SubDivisionId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE prodstage
ADD CONSTRAINT FK_prodstage_prodstage_ProdStagId FOREIGN KEY (ProdStageNextStage)
REFERENCES prodstage (ProdStagId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE prodstage
ADD CONSTRAINT FK_prodstage_techmap_TechMapId FOREIGN KEY (TechMapId)
REFERENCES techmap (TechMapId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE orderstatus (
  OrderStatusId int(11) NOT NULL AUTO_INCREMENT,
  OrderStatusCaption text NOT NULL,
  PRIMARY KEY (OrderStatusId)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE `order` (
  OrderId int(11) NOT NULL AUTO_INCREMENT,
  OrderStatusId int(11) NOT NULL,
  OrderDate datetime NOT NULL,
  NomId int(11) NOT NULL,
  NomCount decimal(20, 10) NOT NULL,
  PRIMARY KEY (OrderId)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

ALTER TABLE `order`
ADD CONSTRAINT FK_order_nom_NomId FOREIGN KEY (NomId)
REFERENCES nom (NomId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `order`
ADD CONSTRAINT FK_order_orderstatus_OrderStatusId FOREIGN KEY (OrderStatusId)
REFERENCES orderstatus (OrderStatusId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE productionlog (
  ProductionLogId int(11) NOT NULL AUTO_INCREMENT,
  ProdStageStartTime datetime NOT NULL,
  ProdStageActualDuration int(11) NOT NULL,
  NomCount decimal(20, 10) DEFAULT NULL,
  OrderId int(11) DEFAULT NULL,
  ProdStagId int(11) DEFAULT NULL,
  TechMapId int(11) DEFAULT NULL,
  PRIMARY KEY (ProductionLogId)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

ALTER TABLE productionlog
ADD INDEX IX_Relationship16 (ProdStagId, TechMapId);

ALTER TABLE productionlog
ADD CONSTRAINT FK_productionlog_order_OrderId FOREIGN KEY (OrderId)
REFERENCES `order` (OrderId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE productionlog
ADD CONSTRAINT FK_productionlog_prodstage_ProdStagId FOREIGN KEY (ProdStagId)
REFERENCES prodstage (ProdStagId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE productionlog
ADD CONSTRAINT FK_productionlog_prodstage_TechMapId FOREIGN KEY (TechMapId)
REFERENCES prodstage (TechMapId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE consumptionlog (
  NomId int(11) NOT NULL,
  ProductionLogId int(11) NOT NULL,
  NomCount decimal(20, 10) DEFAULT NULL,
  PRIMARY KEY (NomId, ProductionLogId)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

ALTER TABLE consumptionlog
ADD CONSTRAINT Relationship19 FOREIGN KEY (NomId)
REFERENCES nom (NomId);

ALTER TABLE consumptionlog
ADD CONSTRAINT Relationship20 FOREIGN KEY (ProductionLogId)
REFERENCES productionlog (ProductionLogId);

CREATE TABLE storage (
  StorageId int(11) NOT NULL AUTO_INCREMENT,
  StorageName text NOT NULL,
  PRIMARY KEY (StorageId)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE storagecontains (
  StorageId int(11) NOT NULL,
  NomId int(11) NOT NULL,
  NumCount decimal(20, 10) NOT NULL,
  PRIMARY KEY (StorageId, NomId)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

ALTER TABLE storagecontains
ADD CONSTRAINT FK_storagecontains_nom_NomId FOREIGN KEY (NomId)
REFERENCES nom (NomId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE storagecontains
ADD CONSTRAINT FK_storagecontains_storage_StorageId FOREIGN KEY (StorageId)
REFERENCES storage (StorageId) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;